### PR TITLE
Added ability to use a proc to handle error

### PR DESCRIPTION
**Pull request by crisward**
I'd like my error to be able to be in json for a json request, and html for html request. So I need to be able to check the request headers. 

I've added the ability to change the error parameter to be a Proc to make this possible.

What do you think?

### CODE REVIEW

**Comment by sdogruyol** [comment]
This is great @crisward 💯  Could you please update the docs with an example of this feature 👍

**Comment by crisward** [comment]
Will do.

**Comment by crisward** [comment]
That ok?

**Comment by sdogruyol** [comment]
LGTM 👍

**Pull request merged**
