### PR TITLE
user can now set http_only and samesite

### LINKED ISSUE #27: Use httpOnly
I think HTTPOnly should be used on the cookie to prevent attacks like [this one](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie#security). Or is there a good reason to not do it?

### LINKED ISSUE #28: Use SameSite
`SameSite: strict` on a cookie prevent it to be sent by requests on other domains. This should probably be used, as I don't see any reason why we would allow requests from other domains (on a CSRF context), and it is [supported by recent browsers](https://caniuse.com/same-site-cookie-attribute).

edit : `SameSite: lax` is probably enough.

### PR DESCRIPTION
**Pull request by henrikac**
This PR adds two additional parameters to the CSRF handler that makes it possible to set httpOnly and SameSite. This is something that was requested in #27 and #28 .

Should close #27, close #28

### CODE REVIEW

**Comment by henrikac** [comment]
@sdogruyol just pinging in case you've missed this PR

**Comment by sdogruyol** [comment]
Thanks @henrikac , I'm actually waiting on https://github.com/kemalcr/kemal-csrf/issues/1#issuecomment-933415442 😄 What do you think?

**Comment by henrikac** [comment]
@sdogruyol I like the idea of including it in kemal-session!

I have tried to do this a few times but I keep getting errors saying that some constant has already been set because adding `require "kemal-csrf"` to kemal-session will set kemal-session constants twice.

**Comment by sdogruyol** [comment]
@henrikac which constants are those?

**Comment by henrikac** [comment]
@sdogruyol `Kemal::Session::Config::INSTANCE` and `Kemal::Session::STORABLE_TYPES` + some of the macros (if not all of them)

**Review by sdogruyol — APPROVED** [review]
Thanks a lot @henrikac 🙏

**Pull request merged**
